//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarDetail
    {
        public int CarID { get; set; }
        public string InventoryType { get; set; }
        public Nullable<int> Price { get; set; }
        public string Year { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Trim { get; set; }
        public string Color { get; set; }
        public string VehicleType { get; set; }
        public string Feature { get; set; }
        public string Milleage { get; set; }
        public string Vin { get; set; }
        public string StockNumber { get; set; }
        public string Transmission { get; set; }
        public string EngineSize { get; set; }
        public string DriveType { get; set; }
        public string ExteriroColor { get; set; }
        public string InteriroColor { get; set; }
        public string Description { get; set; }
        public byte[] image { get; set; }
        public string CarPrice { get; set; }
        public string CarMonthlyPayment { get; set; }
    }
}
