//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanceForm
    {
        public int UserID { get; set; }
        public string DriverLicense { get; set; }
        public string State { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string ResidentialState { get; set; }
        public string ZipCode { get; set; }
        public string MonthlyRent_Mortage { get; set; }
        public string CurrentEmployee { get; set; }
        public string JobTitle { get; set; }
        public string GrossIncome { get; set; }
        public string SocialSecurity { get; set; }
        public string CarYear { get; set; }
        public string CarMake { get; set; }
        public string CarModel { get; set; }
        public string CarMilleage { get; set; }
        public string CarVin { get; set; }
        public string Term { get; set; }
        public string DownPayment { get; set; }
        public string Vehicle { get; set; }
    }
}
