//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellOrTradeInForm
    {
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string YearOfCar { get; set; }
        public string CarMake { get; set; }
        public string CarModel { get; set; }
        public string CarMilleage { get; set; }
        public string CarVin { get; set; }
        public string CarOwnershipStatus { get; set; }
    }
}
